<?php

/**
 * Implements hook_help().
 */
function wechat_help($path, $arg) {
  // re: http://drupal.org/node/767204
}

/**
 * Implements hook menu
 * @return array()
 */
function wechat_menu()
{
    return wechatModule::getMenu();
}

/**
 * Implements hook permission
 * @return [type] [description]
 */
function wechat_permission()
{
    return wechatModule::getPermissions();
}

/**
 * Implements hook theme
 * @param  [type] $existing [description]
 * @param  [type] $type     [description]
 * @param  [type] $theme    [description]
 * @param  [type] $path     [description]
 * @return [type]           [description]
 */
function wechat_theme($existing, $type, $theme, $path)
{
    return wechatModule::getTheme($existing, $type, $theme, $path);
}
